"""Firefox profile detection and user.js management."""

from __future__ import annotations

import configparser
import shutil
import sys
import time
from dataclasses import dataclass
from pathlib import Path

from ssh_socks_cli.config import AppConfig

BLOCK_BEGIN_APPLY = "// BEGIN ssh-socks-cli managed block (do not edit manually)"
BLOCK_END_APPLY = "// END ssh-socks-cli managed block"
BLOCK_BEGIN_RESET = "// BEGIN ssh-socks-cli reset block (restores defaults)"
BLOCK_END_RESET = "// END ssh-socks-cli reset block"

# Back-compat aliases (some callers / tests may still reference the old names)
BLOCK_BEGIN = BLOCK_BEGIN_APPLY
BLOCK_END = BLOCK_END_APPLY


class FirefoxError(Exception):
    """Raised when Firefox profile operations fail."""


@dataclass
class FirefoxProfile:
    name: str
    path: Path
    is_default: bool
    is_relative: bool


def _profiles_root() -> Path:
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "Firefox"
    if sys.platform == "win32":
        import os

        appdata = os.environ.get("APPDATA") or str(Path.home() / "AppData" / "Roaming")
        return Path(appdata) / "Mozilla" / "Firefox"
    # Linux: standard path; Snap/Flatpak users have different paths.
    return Path.home() / ".mozilla" / "firefox"


def _candidate_profile_roots() -> list[Path]:
    """Return all places where Firefox may store profiles on this system."""
    roots = [_profiles_root()]
    if sys.platform.startswith("linux"):
        roots.extend(
            [
                Path.home() / "snap" / "firefox" / "common" / ".mozilla" / "firefox",
                Path.home() / ".var" / "app" / "org.mozilla.firefox" / ".mozilla" / "firefox",
            ]
        )
    return [r for r in roots if r.exists()]


def list_profiles() -> list[FirefoxProfile]:
    """Parse profiles.ini across known Firefox locations."""
    profiles: list[FirefoxProfile] = []
    for root in _candidate_profile_roots():
        ini = root / "profiles.ini"
        if not ini.exists():
            continue
        parser = configparser.ConfigParser()
        try:
            parser.read(ini, encoding="utf-8")
        except configparser.Error:
            continue

        # Firefox 67+ stores the active default in an [Install<HASH>] section
        # matching the install's hash; we take the first Install entry we find.
        default_rel_path: str | None = None
        for section in parser.sections():
            if section.startswith("Install") and parser.has_option(section, "Default"):
                default_rel_path = parser.get(section, "Default")
                break

        for section in parser.sections():
            if not section.startswith("Profile"):
                continue
            name = parser.get(section, "Name", fallback=section)
            rel_path = parser.get(section, "Path", fallback="")
            is_relative = parser.getboolean(section, "IsRelative", fallback=True)
            path = (root / rel_path) if is_relative else Path(rel_path)
            is_default = (
                default_rel_path is not None and rel_path == default_rel_path
            ) or parser.getboolean(section, "Default", fallback=False)
            profiles.append(
                FirefoxProfile(name=name, path=path, is_default=is_default, is_relative=is_relative)
            )
    return profiles


def default_profile() -> FirefoxProfile:
    profiles = list_profiles()
    if not profiles:
        raise FirefoxError(
            "No Firefox profiles found. Is Firefox installed and has it been launched at least once?"
        )
    for p in profiles:
        if p.is_default and p.path.exists():
            return p
    for p in profiles:
        if p.path.exists():
            return p
    raise FirefoxError("Firefox profiles listed in profiles.ini do not exist on disk.")


def build_user_js_block(cfg: AppConfig) -> str:
    """Build the managed user.js block for SOCKS5 + anti-leak."""
    t = cfg.tunnel
    f = cfg.firefox
    bypass = f.bypass_list.replace('"', '\\"')
    dns = str(f.proxy_dns).lower()
    lines = [
        BLOCK_BEGIN_APPLY,
        "// Generated by ssh-socks-cli — see https://github.com/sergioarojasm98/ssh-socks-cli",
        "",
        "// --- Manual SOCKS5 proxy ---",
        'user_pref("network.proxy.type", 1);',
        f'user_pref("network.proxy.socks", "{t.bind_address}");',
        f'user_pref("network.proxy.socks_port", {t.local_port});',
        'user_pref("network.proxy.socks_version", 5);',
        "",
        "// --- DNS leak prevention ---",
        "// Both prefs are set so it works on Firefox <128 (old pref) and 128+ (new pref)",
        f'user_pref("network.proxy.socks_remote_dns", {dns});',
        f'user_pref("network.proxy.socks5_remote_dns", {dns});',
        'user_pref("network.dns.disablePrefetch", true);',
        'user_pref("network.dns.disablePrefetchFromHTTPS", true);',
        "",
        "// --- Force proxy, never fall back to direct (which would leak via the VPN) ---",
        'user_pref("network.proxy.failover_direct", false);',
        'user_pref("network.proxy.allow_bypass", false);',
        'user_pref("network.proxy.allow_hijacking_localhost", true);',
        f'user_pref("network.proxy.no_proxies_on", "{bypass}");',
        "",
        "// --- Disable DNS-over-HTTPS (TRR) which would race the SOCKS tunnel and leak ---",
        'user_pref("network.trr.mode", 5);',
        "",
        "// --- Disable speculative/prefetch connections (they bypass the proxy) ---",
        'user_pref("network.http.speculative-parallel-limit", 0);',
        'user_pref("network.predictor.enabled", false);',
        'user_pref("network.predictor.enable-prefetch", false);',
        'user_pref("network.prefetch-next", false);',
        "",
        "// --- Disable captive portal / connectivity probes that hit Mozilla directly ---",
        'user_pref("network.captive-portal-service.enabled", false);',
        'user_pref("network.connectivity-service.enabled", false);',
    ]
    if f.disable_webrtc:
        lines += [
            "",
            "// --- WebRTC can leak your real IP even through a SOCKS5 proxy ---",
            'user_pref("media.peerconnection.enabled", false);',
        ]
    lines.append(BLOCK_END_APPLY)
    return "\n".join(lines) + "\n"


def build_defaults_block() -> str:
    """Build the reset block that restores every pref we touched to its Firefox default.

    Writing this block and restarting Firefox causes the previously-applied values to be
    overwritten in prefs.js, which is necessary because Firefox persists user_pref values
    to prefs.js at shutdown — simply deleting the apply block is not enough to undo the
    previous session's changes.
    """
    lines = [
        BLOCK_BEGIN_RESET,
        "// Generated by ssh-socks-cli — restores Firefox defaults for every pref we touched.",
        "// Safe to delete after Firefox has been launched once with this block in place.",
        "",
        'user_pref("network.proxy.type", 0);',
        'user_pref("network.proxy.socks", "");',
        'user_pref("network.proxy.socks_port", 0);',
        'user_pref("network.proxy.socks_version", 5);',
        'user_pref("network.proxy.socks_remote_dns", false);',
        'user_pref("network.proxy.socks5_remote_dns", true);',
        'user_pref("network.proxy.failover_direct", true);',
        'user_pref("network.proxy.allow_bypass", true);',
        'user_pref("network.proxy.allow_hijacking_localhost", false);',
        'user_pref("network.proxy.no_proxies_on", "");',
        'user_pref("network.dns.disablePrefetch", false);',
        'user_pref("network.dns.disablePrefetchFromHTTPS", true);',
        'user_pref("network.trr.mode", 0);',
        'user_pref("network.http.speculative-parallel-limit", 6);',
        'user_pref("network.predictor.enabled", true);',
        'user_pref("network.predictor.enable-prefetch", false);',
        'user_pref("network.prefetch-next", true);',
        'user_pref("network.captive-portal-service.enabled", true);',
        'user_pref("network.connectivity-service.enabled", true);',
        'user_pref("media.peerconnection.enabled", true);',
        BLOCK_END_RESET,
    ]
    return "\n".join(lines) + "\n"


def _strip_block(content: str, begin: str, end: str) -> str:
    """Remove a single delimited block, if present."""
    if begin not in content:
        return content
    before, _, rest = content.partition(begin)
    _, _, after = rest.partition(end)
    return before.rstrip() + "\n" + after.lstrip()


def _strip_managed_block(content: str) -> str:
    """Remove any ssh-socks-cli-managed block (apply or reset) from a user.js file."""
    out = _strip_block(content, BLOCK_BEGIN_APPLY, BLOCK_END_APPLY)
    out = _strip_block(out, BLOCK_BEGIN_RESET, BLOCK_END_RESET)
    return out.lstrip("\n")


def _write_with_backup(user_js: Path, new_content: str) -> None:
    if user_js.exists():
        backup = user_js.parent / f"user.js.sshsocks-backup-{int(time.time())}"
        shutil.copy2(user_js, backup)
    user_js.write_text(new_content, encoding="utf-8")


def apply(cfg: AppConfig, profile: FirefoxProfile | None = None) -> Path:
    """Apply SOCKS5 preferences to a Firefox profile's user.js.

    Returns the path to the written user.js.
    """
    profile = profile or default_profile()
    user_js = profile.path / "user.js"
    existing = user_js.read_text(encoding="utf-8") if user_js.exists() else ""
    cleaned = _strip_managed_block(existing)
    new_content = cleaned.rstrip() + ("\n\n" if cleaned.strip() else "") + build_user_js_block(cfg)
    _write_with_backup(user_js, new_content)
    return user_js


def reset(profile: FirefoxProfile | None = None) -> Path:
    """Replace the apply block with a defaults-restoring block.

    This is necessary because Firefox persists applied user_prefs to prefs.js at shutdown,
    so removing the apply block alone would not undo the previous session. The defaults
    block forces Firefox to overwrite prefs.js with Firefox's factory values on next
    startup.
    """
    profile = profile or default_profile()
    user_js = profile.path / "user.js"
    if not user_js.exists():
        raise FirefoxError(f"No user.js found at {user_js}")
    content = user_js.read_text(encoding="utf-8")
    if BLOCK_BEGIN_APPLY not in content and BLOCK_BEGIN_RESET not in content:
        raise FirefoxError("No ssh-socks-cli managed block found in user.js — nothing to reset.")
    cleaned = _strip_managed_block(content)
    new_content = cleaned.rstrip() + ("\n\n" if cleaned.strip() else "") + build_defaults_block()
    _write_with_backup(user_js, new_content)
    return user_js


def purge(profile: FirefoxProfile | None = None) -> Path:
    """Remove any ssh-socks-cli block (apply or reset) entirely.

    Use this only after Firefox has been restarted at least once with a reset block in
    place; otherwise the previously-applied prefs will persist in prefs.js.
    """
    profile = profile or default_profile()
    user_js = profile.path / "user.js"
    if not user_js.exists():
        raise FirefoxError(f"No user.js found at {user_js}")
    content = user_js.read_text(encoding="utf-8")
    if BLOCK_BEGIN_APPLY not in content and BLOCK_BEGIN_RESET not in content:
        raise FirefoxError("No ssh-socks-cli managed block found in user.js — nothing to purge.")
    cleaned = (
        _strip_managed_block(content).rstrip() + "\n"
        if _strip_managed_block(content).strip()
        else ""
    )
    _write_with_backup(user_js, cleaned)
    return user_js
