"""Firefox profile detection and user.js management."""

from __future__ import annotations

import configparser
import shutil
import sys
import time
from dataclasses import dataclass
from pathlib import Path

from ssh_socks_cli.config import AppConfig

BLOCK_BEGIN = "// BEGIN ssh-socks-cli managed block (do not edit manually)"
BLOCK_END = "// END ssh-socks-cli managed block"


class FirefoxError(Exception):
    """Raised when Firefox profile operations fail."""


@dataclass
class FirefoxProfile:
    name: str
    path: Path
    is_default: bool
    is_relative: bool


def _profiles_root() -> Path:
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "Firefox"
    if sys.platform == "win32":
        import os

        appdata = os.environ.get("APPDATA") or str(Path.home() / "AppData" / "Roaming")
        return Path(appdata) / "Mozilla" / "Firefox"
    # Linux: standard path; Snap/Flatpak users have different paths.
    return Path.home() / ".mozilla" / "firefox"


def _candidate_profile_roots() -> list[Path]:
    """Return all places where Firefox may store profiles on this system."""
    roots = [_profiles_root()]
    if sys.platform.startswith("linux"):
        roots.extend(
            [
                Path.home() / "snap" / "firefox" / "common" / ".mozilla" / "firefox",
                Path.home() / ".var" / "app" / "org.mozilla.firefox" / ".mozilla" / "firefox",
            ]
        )
    return [r for r in roots if r.exists()]


def list_profiles() -> list[FirefoxProfile]:
    """Parse profiles.ini across known Firefox locations."""
    profiles: list[FirefoxProfile] = []
    for root in _candidate_profile_roots():
        ini = root / "profiles.ini"
        if not ini.exists():
            continue
        parser = configparser.ConfigParser()
        try:
            parser.read(ini, encoding="utf-8")
        except configparser.Error:
            continue

        # Determine the "Default" profile from any [Install*] section.
        default_rel_path: str | None = None
        for section in parser.sections():
            if section.startswith("Install") and parser.has_option(section, "Default"):
                default_rel_path = parser.get(section, "Default")
                break

        for section in parser.sections():
            if not section.startswith("Profile"):
                continue
            name = parser.get(section, "Name", fallback=section)
            rel_path = parser.get(section, "Path", fallback="")
            is_relative = parser.getboolean(section, "IsRelative", fallback=True)
            path = (root / rel_path) if is_relative else Path(rel_path)
            is_default = (
                default_rel_path is not None and rel_path == default_rel_path
            ) or parser.getboolean(section, "Default", fallback=False)
            profiles.append(
                FirefoxProfile(name=name, path=path, is_default=is_default, is_relative=is_relative)
            )
    return profiles


def default_profile() -> FirefoxProfile:
    profiles = list_profiles()
    if not profiles:
        raise FirefoxError(
            "No Firefox profiles found. Is Firefox installed and has it been launched at least once?"
        )
    for p in profiles:
        if p.is_default and p.path.exists():
            return p
    for p in profiles:
        if p.path.exists():
            return p
    raise FirefoxError("Firefox profiles listed in profiles.ini do not exist on disk.")


def build_user_js_block(cfg: AppConfig) -> str:
    """Build the managed user.js block for SOCKS5 + anti-leak."""
    t = cfg.tunnel
    f = cfg.firefox
    bypass = f.bypass_list.replace('"', '\\"')
    lines = [
        BLOCK_BEGIN,
        "// Generated by ssh-socks-cli — see https://github.com/sergioarojasm98/ssh-socks-cli",
        "",
        "// Manual proxy configuration",
        'user_pref("network.proxy.type", 1);',
        f'user_pref("network.proxy.socks", "{t.bind_address}");',
        f'user_pref("network.proxy.socks_port", {t.local_port});',
        'user_pref("network.proxy.socks_version", 5);',
        f'user_pref("network.proxy.socks_remote_dns", {str(f.proxy_dns).lower()});',
        f'user_pref("network.proxy.no_proxies_on", "{bypass}");',
        "",
        "// Prevent falling back to direct connection (which would leak via the VPN)",
        'user_pref("network.proxy.failover_direct", false);',
        'user_pref("network.proxy.allow_hijacking_localhost", true);',
    ]
    if f.disable_webrtc:
        lines += [
            "",
            "// WebRTC can leak your real IP even through a SOCKS5 proxy",
            'user_pref("media.peerconnection.enabled", false);',
        ]
    lines += [
        "",
        "// Reduce DNS prefetching (would go through the system resolver, i.e., the VPN)",
        'user_pref("network.dns.disablePrefetch", true);',
        BLOCK_END,
    ]
    return "\n".join(lines) + "\n"


def _strip_managed_block(content: str) -> str:
    """Remove a previously-inserted managed block from a user.js file."""
    if BLOCK_BEGIN not in content:
        return content
    before, _, rest = content.partition(BLOCK_BEGIN)
    _, _, after = rest.partition(BLOCK_END)
    # Clean up surrounding blank lines
    result = before.rstrip() + "\n" + after.lstrip()
    return result.lstrip("\n")


def apply(cfg: AppConfig, profile: FirefoxProfile | None = None) -> Path:
    """Apply SOCKS5 preferences to a Firefox profile's user.js.

    Returns the path to the written user.js.
    """
    profile = profile or default_profile()
    user_js = profile.path / "user.js"
    existing = user_js.read_text(encoding="utf-8") if user_js.exists() else ""

    if user_js.exists():
        backup = profile.path / f"user.js.sshsocks-backup-{int(time.time())}"
        shutil.copy2(user_js, backup)

    cleaned = _strip_managed_block(existing)
    new_content = cleaned.rstrip() + ("\n\n" if cleaned.strip() else "") + build_user_js_block(cfg)
    user_js.write_text(new_content, encoding="utf-8")
    return user_js


def reset(profile: FirefoxProfile | None = None) -> Path:
    """Remove our managed block from the profile's user.js."""
    profile = profile or default_profile()
    user_js = profile.path / "user.js"
    if not user_js.exists():
        raise FirefoxError(f"No user.js found at {user_js}")
    content = user_js.read_text(encoding="utf-8")
    if BLOCK_BEGIN not in content:
        raise FirefoxError("No ssh-socks-cli managed block found in user.js — nothing to reset.")
    user_js.write_text(_strip_managed_block(content), encoding="utf-8")
    return user_js
